version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - testableexamples
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 20
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    gomoddirectives:
      replace-allow-list:
        - github.com/gogo/protobuf
      replace-local: true
    gomodguard_v2:
      blocked:
        - module: github.com/golang/protobuf
          recommendations:
            - google.golang.org/protobuf
          reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
        - module: github.com/satori/go.uuid
          recommendations:
            - github.com/google/uuid
          reason: satori's package is not maintained
        - module: github.com/gofrs/uuid
          recommendations:
            - github.com/google/uuid
          reason: gofrs' package is not go module
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    nakedret:
      max-func-lines: 0
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - gocognit
        - lll
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: ^//\s*go:generate\s
      - linters:
          - lll
        source: '[^ ]+ `[^:]+:"[^"]+".*`\s*$'
      - linters:
          - gochecknoglobals
          - gochecknoinits
          - mnd
        path: main.go
      - linters:
          - gochecknoglobals
        path: buildinfo.go
      - linters:
          - bodyclose
          - dupl
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - gosec
          - noctx
          - nomnd
          - wrapcheck
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
      - linters:
          - godot
          - lll
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - errorlint
        source: ^\s+if _, ok := err\.\([^.]+\.InternalError\); ok {
      - linters:
          - gochecknoglobals
        source: (AddToScheme|SchemeBuilder|GroupVersion)\s*=
      - linters:
          - lll
        source: ^//\s*\+kubebuilder:.+
      - linters:
          - gochecknoinits
        path: _types\.go
      - path: (.+)\.go$
        text: _generated\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
