// Code generated by MockGen. DO NOT EDIT.
// Source: deployment.go
//
// Generated by this command:
//
//	mockgen -source=deployment.go -destination=mock_deployment_handler_test.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	types "k8s.io/apimachinery/pkg/types"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockDeploymentHandler is a mock of DeploymentHandler interface.
type MockDeploymentHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDeploymentHandlerMockRecorder
	isgomock struct{}
}

// MockDeploymentHandlerMockRecorder is the mock recorder for MockDeploymentHandler.
type MockDeploymentHandlerMockRecorder struct {
	mock *MockDeploymentHandler
}

// NewMockDeploymentHandler creates a new mock instance.
func NewMockDeploymentHandler(ctrl *gomock.Controller) *MockDeploymentHandler {
	mock := &MockDeploymentHandler{ctrl: ctrl}
	mock.recorder = &MockDeploymentHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeploymentHandler) EXPECT() *MockDeploymentHandlerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeploymentHandler) Delete(arg0 context.Context, arg1 string, arg2 types.NamespacedName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeploymentHandlerMockRecorder) Delete(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeploymentHandler)(nil).Delete), arg0, arg1, arg2)
}

// Publish mocks base method.
func (m *MockDeploymentHandler) Publish(arg0 context.Context, arg1 AvahiPublication) (client.ObjectKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(client.ObjectKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockDeploymentHandlerMockRecorder) Publish(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockDeploymentHandler)(nil).Publish), arg0, arg1)
}
