description: setup go env
name: go-setup
inputs:
  version:
    default: "1.26"
    required: false
    description: "go version to be setup"
runs:
  using: "composite"
  steps:
    - name: setup go
      uses: actions/setup-go@v7.0.0
      with:
        go-version: ${{ inputs.version }}
        cache-dependency-path: go.sum
