apiVersion: v1
kind: Service
metadata:
  name: {{ include "avahi-lb.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: avahi-lb
    app.kubernetes.io/part-of: avahi-lb
    control-plane: controller-manager
  {{- include "avahi-lb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "avahi-lb.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}